# Generated by Django 3.2 on 2021-04-28 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('idVoiture', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelVoiture', models.CharField(max_length=20)),
                ('matricule', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('idChauffeur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('depart', models.CharField(max_length=20)),
                ('arrivee', models.CharField(max_length=20)),
                ('heureDeDepart', models.DateTimeField()),
                ('voiture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chauffeur.voiture')),
            ],
        ),
    ]
